apiVersion: v1
kind: Pod
metadata:
  name: nginx
  #namespace: curso
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    env:
    - name: ENVIRONMENT
      value: "staging"
    - name: HOST_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-secret
          key: root_password
    volumeMounts:
      - name: config
        mountPath: /etc/nginx/conf.d/default.conf
        subPath: default.conf
    resources:
      requests: #Inicia Pod, es la garantía
        memory: "64Mi" #MegaB
        cpu: "200m" #200 miliCores, 1 Core -> 1000 miliCores
      limits: #Limitado por el Kernel Linux
        memory: "128Mi"
        cpu: "500m" #Medio Core
    ports:
    - containerPort: 80
  volumes:
    - name: config
      configMap:
        name: mysql-configmap
